//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASOL.OpenLocationCode.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASOL.OpenLocationCode.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t get Code when latitude or longitude is null..
        /// </summary>
        internal static string CantGetCodeWhenLatitudeOrLongitudeUnset {
            get {
                return ResourceManager.GetString("CantGetCodeWhenLatitudeOrLongitudeUnset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot shorten padded codes: {0}.
        /// </summary>
        internal static string CantShortenPaddedCodes {
            get {
                return ResourceManager.GetString("CantShortenPaddedCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code length must be at least {0}.
        /// </summary>
        internal static string CodeLengthMust {
            get {
                return ResourceManager.GetString("CodeLengthMust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code length must be between {0} and {1}.
        /// </summary>
        internal static string InvalidCodeLength {
            get {
                return ResourceManager.GetString("InvalidCodeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Open Location Code length.
        /// </summary>
        internal static string InvalidOLCLength {
            get {
                return ResourceManager.GetString("InvalidOLCLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported OpenLocationCode version: {0}.
        /// </summary>
        internal static string NotSupportedOLCVersion {
            get {
                return ResourceManager.GetString("NotSupportedOLCVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed Open Location Code is not a valid full code: {0}.
        /// </summary>
        internal static string PassedOLCIsNotFull {
            get {
                return ResourceManager.GetString("PassedOLCIsNotFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed short code is not valid: {0}.
        /// </summary>
        internal static string PassedShortCodeIsNotValid {
            get {
                return ResourceManager.GetString("PassedShortCodeIsNotValid", resourceCulture);
            }
        }
    }
}
